### ISSUE TITLE
feature comment_inifinity_scroll

### ISSUE THREAD

**Issue by harseille** [harseille/WhatSsub#202]
- [x] 댓글 무한 스크롤 기능 추가

**Comment by harseille** [comment]
문제: 댓글 Firabase document snapshot을 저장하는 부분 null setting error

**Comment by oinochoe** [comment]
좋은 해결 방법입니다. 😄  
변수를 따로 두는 경우에는 컴포넌트 내부에 두지말고, 외부에 둬야할 것입니다.
변수 자체를 사용하는 경우가 생기는 것을 최대한 지양해야하구요 😄
